# Numpy jupyter notebook

This is my first notebook and my first time using Numpy.

In [2]:
import numpy as np

# Generates array 0 to 14
a = np.arange(15)
# Shape in 3 x 5 matrix
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
np.array([2,3,4])

array([2, 3, 4])

In [4]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
np.array([[1,2],[3,4]], dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Generate array from 10 to 18, with a step of 2

In [6]:
np.arange(10, 18, 2)

array([10, 12, 14, 16])

Generate array from 10 to 18, 10 numbers

In [7]:
from numpy import pi
np.linspace(10, 18, 10)

array([10.        , 10.88888889, 11.77777778, 12.66666667, 13.55555556,
       14.44444444, 15.33333333, 16.22222222, 17.11111111, 18.        ])

In [8]:
# 3D arrays
a = np.arange(24).reshape(2,3,4)
b = np.arange(24).reshape(2,3,4)
a / b

array([[[nan,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In numpy the arrays **are not copied**, so something like this can happen:

In [9]:
a = np.arange(5)
print("a", a)
b = a
print("b", b)
a[0] = 1111 # Editing a
print("b", b) # Edits also b

a [0 1 2 3 4]
b [0 1 2 3 4]
b [1111    1    2    3    4]


In [10]:
# Get shape of an array
a = np.array([(1.5,2,3), (4,5,6)])
a.shape

(2, 3)

In [11]:
# Numpy array inside another numpy array
a = np.arange(10)
b = np.arange(15)
np.array([a, b]).shape

(2,)

## Random values
`rand` has a uniform distribution (from 0 to 1)  
`randn` has a normal distribution  
https://stackoverflow.com/a/47241066/7924557


In [25]:
# Random values
print(np.random.randint(50)) # Int from 0 to 50
print(np.random.randn())
print(np.random.rand())

18
0.04115370240141676
0.5035889435693205


In [24]:
# e^10
print(np.exp(10))

22026.465794806718
